services:
  web:
    build:
      context: ./src/
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn Spyttest_Shop_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./src/:/usr/src/app/
      - static_files:/usr/src/app/static
      - media_files:/home/app/media/
    # expose:
    #  - 8000
    ports:
      - 8000:8000
    env_file:
      - ./envs/dev.env

volumes:
  static_files:
  media_files: