services:
  web:
    build:
      context: ./src/
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn Spyttest_Shop_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./src/:/usr/src/app/
      - static_files:/usr/src/app/static/
      - media_files:/usr/src/app/media/
    expose:
     - 8000
    # ports:
    #   - 8000:8000
    env_file:
      - ./envs/dev.env

  nginx:
    build:
      context: ./nginx/
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - static_files:/home/app/static/
      - media_files:/home/app/media/

volumes:
  static_files:
  media_files: